### ISSUE TITLE
Distinguish DVA_INTrex by countries s, r AND t

### ISSUE THREAD

**Issue by zauster** [bquast/decompr#12]
Hey,

this is more of a question than an issue. This question has come up in a research project in our institute.
Take for example the third term of the table in the Appendix. This term contains

> DVA in intermediate exports used to produce intermediates that are re-exported to third countries for production of local final goods.

Now, it is clear what countries `s` and `r` are, but is it possible to differentiate (i.e. compute) all possible third countries `t`?
I had a look at the code but I cannot see where the summation over all `t` takes place. Is it even possible (in this framework)?

**Comment by bquast** [comment]
@vkummritz does this sound familiar?
